export async function getBrands() {
  return [
    "Abavas",
    "Absolut",
    "Apple Garden",
    "Augusti",
    "Bacardi",
    "Baileys",
    "Ballantine's",
    "Captain Morgan",
    "Chateau Vintage",
    "Chivas Regal",
    "Craft Brew Co.",
    "Crown Royal",
    "Grey Goose",
    "Hennessy",
    "Highland Distillery",
    "Jack Daniells",
    "Jim Beam",
    "Johnnie Walker",
    "Jägermeister",
    "Patrón",
    "Smirnoff",
  ];
}
